{{- if .Values.karpenter.enabled -}}
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ include "jupyterhub.singleuser.fullname" . }}
  labels: 
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  ttlSecondsUntilExpired: 2592000 # 30 Days=60*60*24*30 Seconds;
  ttlSecondsAfterEmpty: 30
  taints:
    - key: app
      value: {{ .Values.karpenter.requirements.appValue }}
      effect: NoSchedule
  labels:
    provisioned: karpenter
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: {{ .Values.karpenter.requirements.instanceTypes }}
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: {{ .Values.karpenter.requirements.regions }}
    - key: "kubernetes.io/arch"
      operator: In
      values: {{ .Values.karpenter.requirements.arch }}
    - key: "karpenter.sh/capacity-type" 
      operator: In
      values: {{ .Values.karpenter.capacityTypes }}
  limits:
    resources:
      cpu: {{ .Values..karpenter.limits.cpu }}
      memory: {{ .Values.karpenter.limits.memory }} 
  provider:
    subnetSelector:
      {{ .Values.karpenter.provider.subnetSelector }} 
    securityGroupSelector:
      {{ .Values.karpenter.provider.securityGroupSelector }} 
{{- end }}